---
- hosts: all
  tasks:
    - name: COLLECT BIG-IP FACTS
      bigip_device_info:
        gather_subset:
        - system-info
        provider:
          password: "{{ bigip_password }}"
          server: "{{ ansible_host }}"
          user: "{{ bigip_username }}"
      register: device_facts