---
- hosts: all
  tasks:
    - name: Collect BIG-IP information
      bigip_device_info:
        gather_subset:
          - interfaces
          - vlans
        provider:
            server: {f5-server}
            user: {f5-user}
            password: {f5-password}