---
- hosts: all
  tasks:
    - name: COLLECT BIG-IP FACTS
      bigip_device_info:
        gather_subset:
        - system-info
        provider:
          password: "{{ F5_PASSWORD }}"
          server: "{{ F5_SERVER }}"
          user: "{{ F5_USER }}"
      register: device_facts