---
- name: GRAB F5 FACTS
  hosts: all
  connection: local

  tasks:
    - name: show hosts
      debug:
        msg: "DEVICE:{{ansible_host}} USER:{{ansible_user}} PASSWORD:{{ansible_ssh_pass}}"

    - name: Output to a file
      copy:
        content: "{{ansible_user}}"
        dest: "/tmp/n{{inventory_hostname}}-f5.txt"

    - name: Output to a file details
      debug:
        msg: "/tmp/n{{inventory_hostname}}-f5.txt"

    - name: COLLECT BIG-IP FACTS
      bigip_device_facts:
        gather_subset:
          - system-info
        provider:
          server: "{{ansible_host}}"
          user: "{{ansible_user}}"
          password: "{{ansible_ssh_pass}}"
          server_port: 443
          validate_certs: no
      register: device_facts

    - name: DISPLAY COMPLETE BIG-IP SYSTEM INFORMATION
      debug:
        var: device_facts

    - name: DISPLAY ONLY THE MAC ADDRESS
      debug:
        var: device_facts['system_info']['product_version']

    - name: DISPLAY COMPLETE BIG-IP SYSTEM INFORMATION
      debug:
        var: device_facts
      tags: debug
