---
- hosts: all
  tasks:
    - name: COLLECT BIG-IP FACTS
      bigip_device_info:
        gather_subset:
        - system-info
        provider:
          server: {F5_SERVER}
          user: {F5_USER}
          password: {F5_PASSWORD}
      register: device_facts