---
- hosts: all
  tasks:
    - name: COLLECT BIG-IP FACTS
      bigip_device_info:
        gather_subset:
        - system-info
        provider:
          server: "{{private_ip}}"
          user: "{{ansible_user}}"
          password: "{{ansible_ssh_pass}}"
      register: device_facts