---
- hosts: all
  tasks:
    - name: COLLECT BIG-IP FACTS
      bigip_device_info:
        gather_subset:
        - system-info
        provider:
#          password: "{{ ansible_ssh_pass}}"
          server: "{{ inventory_hostname }}"
#          user: "{{ ansible_user }}"
      register: device_facts