---
- hosts: all
  gather_facts: false
  tasks:
  - name: Collect BIG-IP information
    bigip_device_info:
      gather_subset:
        - interfaces
        - vlans
      provider:
        server: F5_SERVER
        user: F5_USER
        password: F5_PASSWORD
  delegate_to: localhost
  - name: Hello World
    debug:
      msg: Hello World