---
- hosts: all
  tasks:
    - name: Collect info
      bigip_device_info:
        gather_subset:
          - interfaces
          - vlans
    - name: Hello World
        debug:
          msg: Hello World