---
- hosts: all
  gather_facts: false
  tasks:
  - name: Set NTP server
    bigip_device_ntp:
      ntp_servers:
        - 192.0.2.23
      provider:
        password: F5_PASSWORD
        server: F5_SERVER
        user: F5_USER
  - name: Hello World
    debug:
      msg: Hello World